name: filtering
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - dask
  - h5py
  - numpy>=1.17.0
  - scipy>=1.2.0
  - xarray
  - netCDF4
  - pykdtree
  - pip:
    - sosfilt
    - parcels @ git+https://github.com/angus-g/parcels.git@openmp-loop#egg=parcels
    - -e .
